Algoritmo PROMEDIO 
	DEFINIR CAL1 Como Entero
	DEFINIR CAL3 COMO ENTERO 
	DEFINIR CAL2 COMO ENTERO 
	DEFINIR PROM COMO REAL 
	ESCRIBIR "INGRESA TU PRIMERA CALIFICACION"
	LEER CAL1 
	ESCRIBIR "INGRESA TU SEGUNDA CALIFICACION"
	LEER CAL2 
	ESCRIBIR "INGRESA TU TERCERA CALIFICACION"
	LEER CAL3
	PROM=(CAL1+CAL2+CAL3)/3
	ESCRIBIR"TU PROMEDIO ES:",PROM
FinAlgoritmo
