Algoritmo SUMA
	DEFINIR a COMO ENTERO 
	DEFINIR b COMO ENTERO 
	DEFINIR r COMO ENTERO 
	
	ESCRIBIR "INGRESA PRIMER NUMERO" 
	LEER a
	ESCRIBIR " INGRESA PRIMER NUMERO" 
	leer b 
	r=a+b 
	ESCRIBIR "EL RESULTADO ES:", r 
	
FinAlgoritmo
